version: "~> 1.0"
os: linux
language: shell
services: docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: hxOkAmBIrZoMtSd0YKRvNwvLF0suzCUNCnjDh5sRnr2n8bDkFT88YEXmMyQklzy7vfZ2k5KZytAwwfs8rk8ZQjETO+Pl/ntnmbhdB1apC2+9Sx7h+Db032Hw8JNXep6cdGA/MA/nW6Z3Xm0WaBfhziTRppQ2U54w5UkIfd9zM+kFmKJWLja2vvpQUvO3XyJ+NRBujttcZmKndQjjMn1qxvqIg0WoQ+SD++9GAN8650d39CUnbl+HBLOOVUSwDSLaxbERxiMgV05Bjj6UpyYZqHK2/t/y68/Lrla1GxlvQlw03VkTbMmGRMUQnRGcZYYT+8Ccql4tqtYNuDshB5oVVkESo8ezAmX9meoDA/9Zajq2CkZ56dGblfSBHDyUuqiv3VnXZ16twdtCNUaSMUIrxpasa10UC4Ulx8eoABqgRBqAVdXQllvhvvAm38bNB9KHE35rFc7ZaNdhOMUMNVx83yMVSFXAFWxPuXlTLChgcikLb5/c23HMImJVmbDos4NJpHLMuCLXIBZxwxSY1NrjIr+JAWko0LNiCVPKu6vm1ffcbAQZGSzfm0HBKsNSXb7LQVyUGelVoZzLs87P5XHa0U3426lw5AzX7ab63r57EOTIitlPTgIL8AdEGZNJk3z+iQfPZSrOWtLiEqQNDFClFyOQDzrr27r74HCUnYaqi5A=
    template:
    - "%{commit_subject}"
    - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
    - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
script:
- ".ci/test.sh"
